### ISSUE TITLE
`WrongRequestBodyStreamSize` when using `concurrentUpload`

### ISSUE THREAD

**Issue by lehins** [axman6/amazonka-s3-streaming#17]
When using `concurrentUpload` it consistently results in `WrongRequestBodyStreamSize` exception, see [AppVeyor build for an example](https://ci.appveyor.com/project/lehins/cache-s3-0gli0/builds/27413116), error in red is "probably" unrelated [stack issue](https://github.com/commercialhaskell/stack/issues/5038). 
```
TransportError - WrongRequestBodyStreamSize 43626199 8388608
```
I suspect the error actually comes from amazonka itself: brendanhay/amazonka#548

I don't really have much more time I can spend on investigating this issue, so I just switched to sequential `streamUpload` and called it a day. But I don't want this problem to go unnoticed so regardless of where the error really comes from I was getting it while using `amazonka-s3-streaming`, so decided to report it here as well.

**Comment by axman6** [comment]
Thanks for letting me know @lehins, hopefully it'll get fixed in Amazonka (though not much has been getting fixed there lately :( )

**Comment by axman6** [comment]
I believe this has now been fixed in Amazonka head as of yesterday.

**Comment by axman6** [comment]
Marking this as closed because I'm pretty sure it's been fixed upstream.

**Comment by endgame** [comment]
Yes, fixed in https://github.com/brendanhay/amazonka/pull/794.
