### ISSUE TITLE
Make a fixed release in 0.1.x (unbreak Stackage LTS)

### ISSUE THREAD

**Issue by koterpillar** [axman6/amazonka-s3-streaming#8]
Stackage LTS doesn't consider upgrading a package from `0.1.x.y` to `0.2.x'.y'` between point LTS releases. 0.1.0.4 doesn't work due to #7.

It would be nice to release 0.1.0.5 with just the fix to #7, so that it gets included in Stackage LTS 8.x. There have been changes to master since that can be considered a breaking change (log level change), so releasing `master` as still 0.1 is probably not correct.

**Comment by koterpillar** [comment]
LTS 9.x has fixed version (0.2.x.y).

**Comment by axman6** [comment]
@koterpillar Apologies, I completely missed this issue come through!
